In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup as BS
import numpy as np
import re
pd.set_option('display.max_colwidth', None)
from datetime import datetime

<span style='background:purple; font-size:25px'>individual csv files</span>

In [2]:
# triangle = pd.read_csv('data/triangle_shape.csv')
# unknown_shape = pd.read_csv('data/unknown_shape.csv')
# unspecified_shape = pd.read_csv('data/unspecified_shape.csv')
# changing_shape = pd.read_csv('data/changing_shape.csv')
# chevron_shape = pd.read_csv('data/chevron_shape.csv')
# cigar_shape = pd.read_csv('data/cigar_shape.csv')
# circle_shape = pd.read_csv('data/circle_shape.csv')
# cone_shape = pd.read_csv('data/cone_shape.csv')
# cross_shape = pd.read_csv('data/cross_shape.csv')
# cube_shape = pd.read_csv('data/cube_shape.csv')
# cylinder_shape = pd.read_csv('data/cylinder_shape.csv')
# delta_shape = pd.read_csv('data/delta_shape.csv')
# diamond_shape = pd.read_csv('data/diamond_shape.csv')
# disk_shape = pd.read_csv('data/disk_shape.csv')
# egg_shape = pd.read_csv('data/egg_shape.csv')
# fireball_shape = pd.read_csv('data/fireball_shape.csv')
# flash_shape = pd.read_csv('data/flash_shape.csv')
# formation_shape = pd.read_csv('data/formation_shape.csv')
# light_shape = pd.read_csv('data/light_shape.csv')
# orb_shape = pd.read_csv('data/orb_shape.csv')
# other_shape = pd.read_csv('data/other_shape.csv')
# oval_shape = pd.read_csv('data/oval_shape.csv')
# rectangle_shape = pd.read_csv('data/rectangle_shape.csv')
# sphere_shape = pd.read_csv('data/sphere_shape.csv')
# star_shape = pd.read_csv('data/star_shape.csv')
# teardrop_shape = pd.read_csv('data/teardrop_shape.csv')

<span style='background:purple; font-size:25px'>combining individual files into 1</span>

In [3]:
# df_list = [triangle, unknown_shape, unspecified_shape, changing_shape,
#                    chevron_shape, cigar_shape, circle_shape, cone_shape,
#                    cross_shape, cube_shape, cylinder_shape, delta_shape,
#                    diamond_shape, disk_shape, egg_shape, fireball_shape,
#                    flash_shape, formation_shape, light_shape, orb_shape,
#                    other_shape, oval_shape, rectangle_shape, sphere_shape,
#                    star_shape, teardrop_shape]

In [4]:
# ufo = pd.concat(df_list)

In [5]:
# ufo.to_csv('ufo.csv', index = False)

<span style='background:purple; font-size:25px'>read in the full (cleaned) dataset csv</span>

In [29]:
ufo = pd.read_csv('data/ufo.csv')

In [27]:
ufo.shape

(145202, 14)

In [ ]:
# convert date column to datetime and create year/month

In [ ]:
ufo.date = pd.to_datetime(ufo['date'], errors = 'coerce')

In [ ]:
ufo.dropna(subset=['date'], inplace=True) # drop rows with none/invalid dates

In [ ]:
current_date = pd.Timestamp(datetime.now())

ufo = ufo[ufo['date'] <= current_date] # get rid of rows with dates after today

In [ ]:
ufo['months'] = ufo.date.dt.strftime('%B') # create month column using months name

In [ ]:
ufo.insert(1, 'month', ufo.months) # move month column to after date

In [ ]:
ufo.drop('months', axis=1, inplace=True) # drop old months column

In [ ]:
ufo['years'] = ufo['date'].dt.year.astype(int) # create years column as int

In [ ]:
ufo.insert(2, 'year', ufo.years)

In [ ]:
ufo.drop('years', axis=1, inplace=True)

In [ ]:
ufo.head(2)

# create cleaned csv

In [23]:
# ufo.to_csv('ufo.csv', index = False)

In [30]:
ufo

,date,month,year,reportlink,city,state,country,shape,duration,description,post_date,images
0,7/29/2023,July,2023,https://nuforc.org/webreports/reports/177/S177093.html,Mallusk,Antrim and Newtownabbey,United Kingdom,Triangle,still current,A very bright light which moved closer. On the top of this light was a triangle reflection that appeared to be on top of the light.,7/29/2023,Yes
1,7/27/2023,July,2023,https://nuforc.org/webreports/reports/177/S177048.html,Plainfield,IN,USA,Triangle,1 minute,2 objects above store.,7/29/2023,NaN
2,7/26/2023,July,2023,https://nuforc.org/webreports/reports/177/S177053.html,Little Falls,MN,USA,Triangle,2 minutes,Saw 2 to 4 triangle craft with bright white lights on the angle tips,7/29/2023,NaN
3,7/25/2023,July,2023,https://nuforc.org/webreports/reports/177/S177081.html,sacramento,CA,USA,Triangle,around 5 min,Silent-more of a slight gush of wind/ triangular object/maybe size of jet/maybe quarter of mile high??,7/29/2023,NaN
4,7/23/2023,July,2023,https://nuforc.org/webreports/reports/176/S176930.html,Buford,GA,USA,Triangle,3+ hours,3 triangle shape white with reddish tint hovering and moving in unison and hovering in the same spot for hours,7/29/2023,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...
145197,6/1/1961,June,1961,https://nuforc.org/webreports/reports/052/S52151.html,NaN,NY,USA,Teardrop,30 minutes,I was 11 yrs old. My Aunt and Uncle and I were driveing from Elmira NY to Bradford PA we were in the hills coming around a bend near a,10/30/2006,NaN
145198,7/10/1958,July,1958,https://nuforc.org/webreports/reports/027/S27374.html,Cheektowaga,NY,USA,Teardrop,10 -20 secs,White teardrop shaped object observed during the daytime,3/21/2003,NaN
145199,6/30/1958,June,1958,https://nuforc.org/webreports/reports/080/S80850.html,Conyers,GA,USA,Teardrop,5 min.,Sighting of a UFO ca. 1958.,5/2/2011,NaN
145200,6/30/1957,June,1957,https://nuforc.org/webreports/reports/048/S48502.html,New York City,NY,USA,Teardrop,i0min,glowing lights lead the way,2/14/2006,NaN
145201,4/9/1957,April,1957,https://nuforc.org/webreports/reports/144/S144824.html,Lahore,NaN,Pakistan,Teardrop,3 seconds,"An object flew by at very high speed and high altitude (over 25,000feet). ((anonymous report))",2/14/2019,NaN

In [ ]:
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\chevron_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\changing_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\unspecified_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\unknown_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\triangle_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\teardrop_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\star_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\sphere_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\rectangle_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\oval_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\other_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\orb_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\light_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\formation_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\flash_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\fireball_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\egg_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\disk_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\diamond_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\delta_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cylinder_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cube_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cross_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cone_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\circle_shape.csv"
"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cigar_shape.csv"

In [10]:

# List of file paths
file_paths = [
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\chevron_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\changing_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\unspecified_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\unknown_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\triangle_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\teardrop_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\star_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\sphere_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\rectangle_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\oval_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\other_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\orb_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\light_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\formation_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\flash_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\fireball_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\egg_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\disk_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\diamond_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\delta_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cylinder_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cube_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cross_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cone_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\circle_shape.csv",
    r"C:\Users\Adam\Documents\NSS\python\projects\ufo\data\cigar_shape.csv"
]

# Create an empty list to store DataFrames
dataframes = []

# Loop through file paths and read CSVs into DataFrames
for file_path in file_paths:
    df = pd.read_csv(file_path)
    dataframes.append(df)

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

In [12]:
combined_df['shape'] = combined_df['shape'].str.lower()

In [14]:
combined_df.loc[combined_df['shape'] == 'other']

,date,reportlink,city,state,country,shape,duration,description,post_date,images
52548,7/27/23 06:15,reports/177/S177039.html,Dawson,WV,USA,other,45 seconds,Glowing rocket shaped craft,7/29/23,NaN
52549,7/23/23 21:24,reports/176/S176912.html,Noble,OK,USA,other,2 minutes approximately,"I took a photograph first and then a video. I cannot rationalize what I saw. It looked foggy and it is cloudless, changing in intens",7/29/23,Yes
52550,7/20/23 23:30,reports/176/S176955.html,Yelm,WA,USA,other,A few minutes,"I was in my room and I saw 3 almost translucent/holographic small sort of bell-shaped objects appear, hover around",7/29/23,Yes
52551,7/20/23 20:31,reports/176/S176952.html,St Catharines,ON,Canada,other,15-20 Minutes,Long rock type of material,7/29/23,NaN
52552,7/17/23 01:15,reports/176/S176821.html,Elvanfoot,Scotland,United Kingdom,other,5 minutes,"Bright white thing above the horizon, it was morphing into different shapes while flashing very bright white & two red lights (fixed)",7/29/23,NaN
...,...,...,...,...,...,...,...,...,...,...
62500,NaN,reports/148/S148478.html,Nahunta,GA,USA,other,NaN,((HOAX??)) ((NUFORC Note: Source of report provides no information. PD)),9/6/19,NaN
62501,NaN,reports/084/S84341.html,VÃ¤sterÃ¥s (Sweden),NaN,Sweden,other,NaN,"""Star"" that lights up and disappears. ((NUFORC Note: Date and time not reported. Possible flare from an Iridium satellite? PD))",10/19/11,NaN
62502,NaN,reports/034/S34436.html,Key West,FL,USA,other,one minute,"I lived on a shallow-water marshland in Key West, right opposite to the end of the runway-takeoff from the Key West airport.\r\n\r\n I knew",1/17/04,NaN
62503,NaN,reports/163/S163863.html,Shoreline,WA,USA,other,1 minute,"Saw a low fast moving object going low over the brown wooden fence that runs along the outside of my bedroom window, did not see this b",8/16/21,NaN
62504,NaN,reports/163/S163796.html,Rockville,MD,USA,other,0:00-3:00,intermittent blinking (.5 of a second) objects which move horizontally across the sky at a moderate/swift rate.,7/31/21,NaN

In [5]:
text_to_add = 'https://nuforc.org/webreports/'

# Update rows where shape is 'Other'
combined_df.loc[combined_df['shape'] == 'Other', 'shape'] = text_to_add + combined_df.loc[combined_df['shape'] == 'Other', 'shape']

# Print the modified DataFrame

                            date  \
0                  7/18/23 03:15
1                  7/10/23 22:00
2                   7/3/23 23:00
3                  6/30/23 14:00
4                  6/28/23 00:47
...                          ...
145554           summer/49 11:00
145555  spring/summer/1995 08:00
145556           7/19?2019 07:45
145557            12/24/98 06:24
145558               DITTO 03:00

                                                    reportlink  \
0       https://nuforc.org/webreports/reports/176/S176823.html
1       https://nuforc.org/webreports/reports/176/S176725.html
2       https://nuforc.org/webreports/reports/176/S176578.html
3       https://nuforc.org/webreports/reports/176/S176555.html
4       https://nuforc.org/webreports/reports/176/S176500.html
...                                                        ...
145554   https://nuforc.org/webreports/reports/009/S09687.html
145555   https://nuforc.org/webreports/reports/003/S03223.html
145556  https://nuforc.org/webreports/reports/147/S147744.html
145557   https://nuforc.org/webreports/reports/005/S05240.html
145558   https://nuforc.org/webreports/reports/060/S60714.html

                                                                city state  \
0                                                     Fredericksburg    VA
1                                                                NaN    ON
2                                                            Lincoln    NE
3                                                         Winnemucca    NV
4                                                             Lamont    CA
...                                                              ...   ...
145554                                                      New Troy    MI
145555  Oklahoma City (northwest of; approximately over Lake Hefner)    OK
145556                                                    Smithsburg    MD
145557                                                      Bartlett    IL
145558                                  Nottinghamshire (UK/England)   NaN

                     country    shape               duration  \
0       International Waters  Chevron             45 seconds
1                     Canada  Chevron                3 hours
2                        USA  Chevron                  30sec
3                        USA  Chevron  About 5 to 10 minutes
4                        USA  Chevron             30 seconds
...                      ...      ...                    ...
145554                   USA    Cigar                unknown
145555                   USA    Cigar              2 minutes
145556                   USA    Cigar             45 seconds
145557                   USA    Cigar               25 secs.
145558        United Kingdom    Cigar                 30 MIN

                                                                                                                                    description  \
0                                                                               Was watching ISS live stream and these lights drew my attention
1                             I saw a triangular or chevron cheaper object, while walking in a low lit area.It moved in all directions quickly.
2          Was the coolest technology Ive ever seen it was translucent & reflected the smoke above it from fireworks on the bttm and the stars
3          It started out on the West side if Winnemucca Mountain , and ended at East Winnemucca Blvd  They were doing maneuvers, and vanished.
4                                                                      Craft was flying around 200 ft off ground on the north side of highway 5
...                                                                                                                                         ...
145554  Large (at least 500 yards long) cigar shaped object with two rows of approx 100 windows. Light metallic brown color. Issued blue light.
145555  observed a darkred,almost purple,blimp shaped object with a belt of panel-like windows that might have been like bluish lights in them,
145556  It was cigar shaped approx 75 to 100 ft long  silver in color no external fins  altitude around 10 thousand feet  clear sky and dayligh
145557  at 6:24 P.M. i saw a cigar shaped object w/ red lights and one white light on the nose,it was moving west/northwest.very fast and slowe
145558                                                           LONG TIME ON LONLEY ROAD WITH UFO ONLY 300 FEET ABOVE MY HEAD AS BIG AS A BUS.

       post_date images
0        7/29/23    Yes
1        7/29/23    NaN
2        7/10/23    NaN
3        7/10/23    NaN
4        7/10/23    NaN
...          ...    ...
145554   10/2/99    NaN
145555   1/28/99    NaN
145556   7/25/19    NaN
145557   2/16/99    NaN
145558   1/21/08    NaN

[145559 rows x 10 columns]

In [15]:
second_df = combined_df